{{- $shouldCreateSecret := include "camundaPlatform.shouldCreateSecret" (dict "newSecretConfig" .Values.global.identity.auth.connectors.secret "oldPassword" "" "oldExistingSecret" .Values.global.identity.auth.connectors.existingSecret "context" .) }}
{{- if and (.Values.global.identity.auth.enabled) (eq $shouldCreateSecret "true") }}
{{- $secretName := include "camundaPlatform.identitySecretName" (dict "context" . "component" "connectors") }}
{{- $secretKey := include "camundaPlatform.getSecretKey" (dict "newSecretConfig" .Values.global.identity.auth.connectors.secret "oldExistingSecretKey" .Values.global.identity.auth.connectors.existingSecretKey "defaultKey" "identity-connectors-client-token" "context" .) }}
{{- $isUsingPlainPassword := include "camundaPlatform.isUsingPlainPassword" (dict "newSecretConfig" .Values.global.identity.auth.connectors.secret "oldPassword" "" "context" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "camundaPlatform.identityLabels" . | nindent 4 }}
  annotations:
    {{- if eq $isUsingPlainPassword "true" }}
    io.camunda.zeebe/warning: "Using plain-text password is not recommended for production. Consider using existingSecret instead."
    {{- end }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.identity.auth.connectors.secret.password }}
  {{ $secretKey }}: {{ .Values.global.identity.auth.connectors.secret.password | b64enc }}
  {{- else }}
  {{ $secretKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" $secretKey "length" 10 "providedValues" (list "global.identity.auth.connectors.existingSecret") "context" $) }}
  {{- end }}
{{- end }}